# Welcome to Lab: Experimental Design 👨‍🔬⚗️🧪

Before this lab section, you completed the "Hello Survey" based on the questions you generated with your groups.  This week, you will do an analysis of the results and explore techniques to do experimental design in Python! You'll also learn about an extreme case of confounding called Simpson's Paradox while analyzing a new dataset!

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab TA, your CAs, your lab group, and the professors (Prof. Wade and Prof. Karle), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

<hr style="color: #DD3403;">

In [0]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Mehmet"
ca1_name = "Bella"
ca2_name = "Jonah"
ca3_name = ""

# Say hello to each other!
# - Groups of 3 are ideal :)
# - However groups of 2 or 4 are fine too!
partner1_name = "Pranav"
partner1_netid = "pranavn9"

partner2_name = "Jackson"
partner2_netid = "jg86"

partner3_name = ""
partner3_netid = ""

# Which lab section are you in? Record it below! It should start with a Y and have 
# 2 numbers after the Y. If you're unsure - ask your TA/CAs!
lab_section = "Y05"

<hr style="color: #DD3403;">

# Part 1: Hello Dataset Analysis

In lab last week, you created a series of questions that made up the **"Hello Dataset"**.  Before lab, you completed this survey along with the entire class.  Today, you're going to do analysis on this dataset! :)

## Your Binary Question Analysis

You will be analyzing the **binary question** your group asked the class from `lab_pandas` -- record it below.  If multiple people from your group had different binary questions, decide which one to use and record that question below.

*(Do you have a pet?)*

### Puzzle 1.1: Load the Hello Dataset

The "Hello Dataset" is available here:
```
http://waf-server-01.cs.illinois.edu/static/hello-fa25.csv
```

Load this dataset into a DataFrame called `df` -- and **don't forget to import pandas**! :)

In [1]:
import pandas as pd
df=pd.read_csv("http://waf-server-01.cs.illinois.edu/static/hello-fa25.csv")
df

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
0,Prof. Wade,Lecture,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Sweeden,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin
1,Prof. Karle,Lecture,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Maldives,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives
2,Muhammad,Y20,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Malaysia,Green,Sleeping,Hip hop,Husky,Electrical Engineering,Kanye West,Instagram,Minecraft,Switzerland
3,Jake,Y10,Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Norway,Yellow,Hang Out With Friends,Indie Music,Llama,Electrical Engineering,Tame Impala,Instagram,Volleyball,Switzerland Alps
4,Shourya,Y04,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,UAE,Red,Youtube,Indie pop,Wolf,Astrophysics,Cigarettes after sex,Instagram,Spy,Iceland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,CA Emily,"Y07, Y36, Y39",Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,Movies,...,Poland,Purple,Friends,Pop,Bunny,Electrical Engineering,Ariana Grande,Instagram,Stardew Valley,Italy
1138,TA Junyu,"Y34, Y39",Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,China,pink,movies,Focus,"I’d be an octopus: curious, adaptable, great a...",CS,Taylor Swift,twitter,Overcooked,Hawaii
1139,TA Yangchang,Y13 Y43,Heads,Vanilla,Morning,Even,No,Summer,Not in Gies,Movies,...,Australia,Red,Workout,Pop,Eagle,CS,Chopin,Wechat,Brawl Stars,Hawaii
1140,TA Tina,Y32;Y36,Heads,Vanilla,Morning,Odd,No,Summer,Not in Gies,Movies,...,China,blue,exercising and runing,rock,fish,cs,ed sheeran,wechat,overcooked,Europe
1141,TA Jackson,Y29 Y36,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Signapore,Red,Research,Metal,Penguin,Art,Les Claypool,Reddit,Sea of Thieves,Italy

### Find The Variable for Your Question

The command `df.columns.tolist()` will **list all of the columns (variables)** in a DataFrame.  Use `df.columns.tolist()` and read the output until you find the column name for your binary question.

- You may see the message: `Output exceeds the __size limit__. Open the full output data __in a text editor__`
- If you do, click the **`__in a text editor__`** link to open the whole list in a new tab.

In [2]:
df.columns.tolist()

['Name',
 'Lab',
 'When flipping a coin, heads or tails?',
 'Is your favorite ice cream flavor chocolate or vanilla?',
 'Do you like morning or night?',
 'Is your favorite number even or odd?',
 'Do you have a pet?',
 'Do you prefer summer or winter?',
 'Are you in the Gies College of Business?',
 'Do you prefer Movies or TV shows?',
 'Do you prefer pizza or hamburgers?',
 'You describe yourself as:',
 'Do you prefer sweet or salty food?',
 'Do you eat breakfast?',
 'Do you speak a second language?',
 'Do you prefer cats or dogs?',
 'Do you prefer Italian or Mexican food?',
 'Cookies or Brownies?',
 'Do you like apples or bananas?',
 'Waffles or pancakes?',
 'Night Owl or Early Bird?',
 'Did you do high school in Illinois?',
 'Do you typically shower in the morning or at night?',
 'Do you prefer sweet or savory food?',
 'What month is your birthday?',
 'Do you use a Mac or Windows Laptop?',
 'Do you like pizza or pasta?',
 'Do you wear glasses?',
 'Fall or spring season?',
 'Do you prefer pink or blue?',
 'Does your UIN end with an even or odd number?',
 'Do you use corrective lenses (contacts/glasses)?',
 'Do you prefer Apple Music or Spotify?',
 'Do you have any siblings?',
 'Are you from Chicago?',
 'Pick a number: One or Two.',
 'Do you prefer basketball or football?',
 'Do you prefer the beach or mountains?',
 'Do you prefer breakfast or dinner?',
 'Do you prefer Coca Cola or Pepsi?',
 'Do you prefer coffee or tea?',
 'Are you an extrovert or introvert?',
 'Do you prefer hotdogs or hamburgers?',
 'Do you like Messi or Ronaldo?',
 'Have you ever been outside of United States?',
 'Do you have more than 1 sibling?',
 'Does pineapple belong on pizza?',
 'Do you live in Urbana or Champaign?',
 'Do you prefer sunny or rainy days?',
 'Red or Blue?',
 'Is your DISCOVERY lab the last class of your day?',
 'Have you had your 19th birthday?',
 'Are you a Statistics Major?',
 'Are you currently wearing shorts?',
 'Are you from Chicago or the suburbs?',
 'Are you registered for the 9am or 11am lecture?',
 'Are you team Edward or team Jacob?',
 'Cold Coffee or Hot Coffee?',
 'Did you go to the football game against WIU?',
 'Cookies or Ice Cream?',
 'Do you prefer urban or rural areas?',
 'Do you prefer creamy or chunky peanut butter?',
 'Dunkin or Starbucks?',
 'Football or soccer?',
 'Fruits or vegetables?',
 'Do you prefer gold or silver jewelry?',
 'Do you prefer hot or cold weather?',
 'Do you prefer in person or online classes?',
 'Do you prefer Instagram Reels or TikTok?',
 'Do you prefer Kendrick Lamar or Drake?',
 'Do you prefer ketchup or honey mustard?',
 'Do you prefer Lebron James or Michael Jordan?',
 'Do you eat beef?',
 'Do you exercise regularly?',
 'Do you game on a PC or Console?',
 'Do you have a brother?',
 'Do you prefer being hot or cold?',
 'Do you like chocolate ice cream?',
 'Do you like cilantro or not?',
 'Do you prefer DC or Marvel?',
 'Do you like ice cream?',
 'Do you like Mint Chocolate Chip ice cream?',
 'Do you like pizza?',
 'Red or Green?',
 'Do you like running?',
 'Do you like school?',
 'Sweet food or spicy food?',
 'Do you live in a dorm or apartment?',
 'Do you live in University Housing or Private Housing?',
 'Do you prefer Xbox or Playstation?',
 'Do you prefer travelling by plane or cruise?',
 'Breakfast or Lunch?',
 'Do you prefer lunch or dinner?',
 'Do you prefer mild or spicy food?',
 'Nike or Adidas?',
 'Do you prefer pens or pencils?',
 'Purple or orange?',
 'Red or Black?',
 'Sausage or Bacon?',
 'Skittles or M&Ms?',
 'Soup or Salad?',
 'Chicken or steak?',
 'Tacos or Burritos?',
 'Do you prefer the window or aisle seat on an airplane?',
 'TikTok or Instagram?',
 'Do you prefer to work remotely or in office?',
 'What comes first, milk or cereal?',
 'Do to typically go to bed before or after 11pm?',
 'How should toilet paper be rolled?',
 'Have you eaten lunch today?',
 'Headphones or Earbuds?',
 'If you had to go to sleep at the same time every night, would it be ...',
 'Is a hot dog a sandwich?',
 'Is a tomato a fruit or a vegetable?',
 'Is Apple better than Android?',
 'Is Tuesday or Wednesday better?',
 'Is your birth date odd or even?',
 'Is your birth MONTH even or odd?',
 'Is your birthday in the first fifteen days of the month?',
 'Matcha or Coffee?',
 'Hoodie + Shorts or Shirt + Pants?',
 'Noodles or Rice?',
 'Savory or sweet breakfast?',
 'Was Illinois Your Dream School?',
 'Sights and Sounds: Were you Orange or Blue?',
 'Seals or Penguins?',
 'Orange or Blue?',
 'Soda or Juice?',
 'North Pole or South Pole?',
 'Prefer Lecture of Lab in DISCOVERY?',
 'Computer Science or Statistics?',
 'Do you prefer Mom or Dad?',
 'Would you rather be Courageous Pizza or Honest Broccoli?',
 'Would you rather be too hot or too cold?',
 'When do you go to the gym?',
 'Orange or Apple?',
 "Would you rather know how you die or know when you'd die?",
 'Which of the following descriptions best matches your favorite movie?',
 'Is math red or blue?',
 'Do you get closer to 6 or 7 hours of sleep?',
 'How many classes are you taking this semester?',
 'How many credit hours are you taking?',
 'How many hours do you sleep in a night?',
 'How many siblings do you have?',
 'Pick a number between 1 and 10.',
 'What is your shoe size (US size)?',
 'How many cups (8 oz.) of water do you drink a day?',
 'What number do you consider as an unlucky number?',
 'How many people is the ideal number of people at a party?',
 'What is your phone battery percentage currently at?',
 'Besides the US, what country would you like to live in?',
 'What is your favorite color?',
 'Favorite way to spend your free time?',
 'What genre of music do you like the most?',
 'If you were an animal, which would you be? / What is your spirit animal?',
 'What do you think is the hardest major at UIUC?',
 'Who is your favorite music artist?',
 "What's your favorite social media app?",
 'What is your favorite game to play (either video game or IRL)?',
 'Where is your dream vacation spot?']

### Puzzle 1.2: Record the Variable for Your Question

In the cell below, record your question's column name as a **string** variable named `analysis_column`.  You'll need that exact column name to reference data from that cell.

In [3]:
analysis_column =  "Do you have a pet?"
analysis_column

'Do you have a pet?'

### 🔬 Test Case Checkpoint 🔬

In [4]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error in your output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('df' in vars()), "You do not have a DataFrame called `df`."
assert(len(df) >= 1142 and len(df) < 1212), "You have not loaded the correct Hello Dataset."
assert(analysis_column in df), "Make certain your analysis_column string is EXACTLY as it appears in the Hello Dataset."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.3: Column Subset- View Only Your Question's Responses

To begin your question's analysis, you first want to focus only on your question's column.  In lecture, we have primarily focused on creating subsets of rows. However, you can also create a subset of columns!

To get a DataFrame with a specific column from `df`, you can use the syntax:
```
df[ ["column name"] ]
```
- Notice the **double set of square brackets**.  You need the outer set for `df`, and the inner set for the column name.
- Because we've already loaded your question into `analysis_column`, you won't need the quotation marks this time.
- You can find this syntax under the "Subset Variables (Columns)" on your Pandas cheat sheet!

With the `analysis_column` variable from above, use Python to display only the column you're analyzing.  This will make it easy to see what the two options were for your question:

In [5]:
df[[analysis_column]]

     Do you have a pet?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                    No
...                 ...
1137                Yes
1138                 No
1139                 No
1140                 No
1141                Yes

[1142 rows x 1 columns]

### Puzzle 1.4: DataFrame: Group One

Create a DataFrame, `df1`, that contains everyone who picked the first option of your two answers.  *(Make sure to make this a subset of the original `df`, and not just your one column.)*

In [13]:
df1 = df[df[analysis_column] == "Yes"]
df1

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
0,Prof. Wade,Lecture,Heads,Chocolate,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Sweeden,Purple,Nerding Out,Pop EDM,Eagle,Physics,Taylor Swift,YouTube,Factorio,Mountain Cabin
1,Prof. Karle,Lecture,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Maldives,pink,with people!!!,pop,sloth,computer science,Taylor Swift,instagram,cards,Maldives
2,Muhammad,Y20,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,Movies,...,Malaysia,Green,Sleeping,Hip hop,Husky,Electrical Engineering,Kanye West,Instagram,Minecraft,Switzerland
3,Jake,Y10,Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Norway,Yellow,Hang Out With Friends,Indie Music,Llama,Electrical Engineering,Tame Impala,Instagram,Volleyball,Switzerland Alps
5,Ezio,Y02,Tails,Vanilla,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,Denmark,Baby Blue,Watching TV,R&B,Eagle,ECE,Coldplay,Snap,Soccer,Banff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1133,TA Nathan,"Y16, Y18",Tails,Vanilla,Morning,Even,Yes,Summer,Not in Gies,Movies,...,Germany,Blue,Outside,Indie,Tiger,Physics,Lustra,X,Minecraft,Greece
1135,CA Bella B,Y05 Y16 Y32,Heads,Chocolate,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,Italy,purple,run,pop,butterfly,cheme,sabrina carpenter,tiktok,orangatang,Italy
1136,TA Matt,"Y04, Y08",Heads,Chocolate,Morning,Odd,Yes,Summer,Not in Gies,Movies,...,Canada,Blue,Reading,Alternative Rock,Grizzly bear,Any major you try your you're absolute hardest in,Creedance Clearwater Revival,Instagram,Call of Duty Warzone,warm beach
1137,CA Emily,"Y07, Y36, Y39",Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,Movies,...,Poland,Purple,Friends,Pop,Bunny,Electrical Engineering,Ariana Grande,Instagram,Stardew Valley,Italy
1141,TA Jackson,Y29 Y36,Heads,Vanilla,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Signapore,Red,Research,Metal,Penguin,Art,Les Claypool,Reddit,Sea of Thieves,Italy

### Puzzle 1.5: DataFrame: Group Two

Create a new DataFrame, `df2`, that contains everyone who picked the other answer:

In [15]:
df2 = df[df[analysis_column] == "No"]
df2

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
4,Shourya,Y04,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,UAE,Red,Youtube,Indie pop,Wolf,Astrophysics,Cigarettes after sex,Instagram,Spy,Iceland
6,Angela,Y39,Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,Singapore,dark blue,watch movie,country,koala,ece,lainey Wilson,Instagram,Kirby,Hawaii
7,Caleb,Y08,Tails,Vanilla,Night,Odd,No,Summer,In Gies College of Business,Movies,...,Spain,Red,With friends,Country,Lion,CS+Bioengineering,NF,Youtube,Volleyball,Carribean
8,Andrew,Y20,Heads,Vanilla,Night,Odd,No,Winter,In Gies College of Business,Movies,...,China,dark green,learn something new and be productive,R&B,wolf,Engineering,Jay Chou,insta,none,hawaii
9,Arwa,Y35,Heads,Chocolate,Morning,Even,No,Summer,In Gies College of Business,TV Shows,...,Singapore,Blue,With my friends,Indie,Bunny,Mechanical Engineering,Dominic Fike,Instagram,Blackjack,Malaysia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129,CA Sophia,"Y04, Y10",Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,greece,purple,working out,indie,jaguar,ECE,clairo,Instagram,fortnite,aruba
1134,CA Urvi,Y04,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,London,periwinkle,something crafty,Pop,Lynx,Chemical Engineering,Taylor Swift,Pinterest,Linkedin Games Tango and Queens,Greece
1138,TA Junyu,"Y34, Y39",Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,China,pink,movies,Focus,"I’d be an octopus: curious, adaptable, great a...",CS,Taylor Swift,twitter,Overcooked,Hawaii
1139,TA Yangchang,Y13 Y43,Heads,Vanilla,Morning,Even,No,Summer,Not in Gies,Movies,...,Australia,Red,Workout,Pop,Eagle,CS,Chopin,Wechat,Brawl Stars,Hawaii
1140,TA Tina,Y32;Y36,Heads,Vanilla,Morning,Odd,No,Summer,Not in Gies,Movies,...,China,blue,exercising and runing,rock,fish,cs,ed sheeran,wechat,overcooked,Europe

### Puzzle 1.6: Calculations

What percentage of people chose each of your two binary options? Do each calculation and store each of the results in a variable.

In [18]:
#People that chose yes
y = (554/1142) * 100
n = (587/1142) * 100
print(y)
print(n)

48.51138353765324
51.40105078809106

<hr style="color: #DD3403;">

## Part 2: Creating Treatment and Control Groups

For Part 2 of this lab, we will consider the "Hello Dataset" to be a pre-survey of randomly selected participants for an upcoming experiment.  In lecture, you learned that a good experiment will split the participants into two groups: the "treatment" group and the "control" group.

Remember that it's best to have both groups and it's best to divide them randomly!

- The "treatment" group is the group of people who receive the treatment!
- The "control" group is a comparison group that does not receive the treatment! We always want to collect data from our control group to compare to the treatment group.

### Part 2.1: Selecting a Treatment Group

**Randomly** select half (50%) of the participants from our original `df` to be in the treatment group and place them into a DataFrame called `treatment`.
- Remember, you can ask your CAs, TAs, or use your **pandas cheat sheet** to help you out!

In [19]:
treatment = df.sample(frac=0.5)
treatment

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
64,Sebastian,Y40,Tails,Vanilla,Night,Odd,Yes,Summer,Not in Gies,TV Shows,...,Greece,Orange,With friends,Rap,A dog,Mechanical Engineering,Micheal Jackson,YouTube,Uno,The Vatican
1109,CA Bella,Y22,Tails,Chocolate,Morning,Odd,Yes,Winter,In Gies College of Business,TV Shows,...,Switzerland,Blue,With friends,Rock,Corgi,Neural engineering,SZA,TikTok,Monopoly,St.Lucia
1069,Runzhe Zhao,Y04,Heads,Vanilla,Morning,Even,No,Summer,Not in Gies,TV Shows,...,China,Blue,"Play basketball until exhausted, having a grea...",Rock music,Elephant,CS,Jay Chou,Wechat,Valorant,Near the sea with beach
808,Thomas,Y40,Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Peru,Black,Investing,House,Honey Badger,CS + Physics,Melly Mike,NaN,Basketball,Alaska
419,Brendan,Y11,Heads,Chocolate,Morning,Even,Yes,Summer,Not in Gies,TV Shows,...,Malta,Green,Video Games,Electronic,Robin,Electrical Engineering,Tame Impala,Youtube,Minecraft,Hawaii
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,Angel,Y12,Heads,NaN,Night,Odd,Yes,Winter,Not in Gies,TV Shows,...,mexico,black,Spend it with my girl,Regeton,Dragon,Computer Science,Rauw Alejandro,Snapchat,Minecraft,Dubai
462,Omar,Y35,Heads,Vanilla,Night,Odd,Yes,Summer,Not in Gies,Movies,...,México,Purple,Hanging out with friends,Corridos,Cat,CS,Mac Demarco,Tiktok,Apex legends,Japan
216,Liva,Y33,Heads,Chocolate,Morning,Odd,No,Summer,In Gies College of Business,TV Shows,...,spain,red,hang out with friends,rap,cheetah,english,drake,instagram,lacrosse,spain
76,Danny,Y12,Heads,Chocolate,Morning,Even,No,Winter,Not in Gies,Movies,...,Greece,blue,gym,country,Dog,computer science,drake,youtube,chess,greece
43,Ryan,Y19,Tails,Chocolate,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Thailand,Blue,Sleeping,Hip-Hop,Cheetah,ECE/CE,Drake,Instagram,4 square,Hawaii

### Part 2.2: Select a Control Group

Using the **exact same technique and syntax** as you did above, also randomly select half (50%) of the participants to be in the control group.  Place them into a DataFrame called `control`. 

*For now, it's okay if there are people who are in both groups.*

In [21]:
control = df.sample(frac=0.5)
control

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
46,Megan,Y09,Heads,Chocolate,Night,Even,Yes,Summer,Not in Gies,TV Shows,...,Finland,Gold,Video Games,No music,Owl,Medical,I dont listen to music,Discord,Minecraft,Orlando
680,Jordy,Y32,Tails,Vanilla,Morning,Even,No,Winter,Not in Gies,TV Shows,...,Iceland,Purple,Weightlifting,Country,Dog,CS,Godsmack,Youtube,Minecraft,Rocky Mountains
82,Josh,Y29,Tails,NaN,Morning,Odd,Yes,Summer,Not in Gies,Movies,...,Canda,Lavender blue,Being active,Christian Worship,Wolf,Chemical Engineering,Jorge Rivera-Herrans,Instagram,Ultimate Frisbee,Alaska Backpacking Trip
1074,Drew,Y29,Heads,Chocolate,Night,Odd,Yes,Summer,Not in Gies,Movies,...,Spain,Olive Green,with my gf,pop rock,Otter,aerospace engineering,Kings of Leon,Instagram,tennis,Greece
1119,TA Sayantani,"Y17, Y31",Heads,Chocolate,Night,Odd,No,Summer,Not in Gies,Movies,...,Iceland,Pink,With friends,Pop,Bunny,ECE,Taylor Swift,Instagram,Minecraft,Tokyo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,Cayden,Y17,Tails,Vanilla,Night,Odd,No,Summer,In Gies College of Business,Movies,...,Italy,Blue,Video games,Idk,Penguin,Engineering,Steve lacy,Snapchat,NBA 2k,Almafi coast
765,Aryan,Y23,Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Canada,Blue,Basketball,Rap,Tiger,Physics,d4vd,Instagram,Clash Royale,Singapore
573,Ariana,Y16,Heads,Vanilla,Morning,Odd,Yes,Summer,Not in Gies,Movies,...,Montenegro,pink,reading,indie,cat,math,The Marias,tiktok,minecraft,Japan
695,Lauryn,Y40,Tails,Vanilla,Night,Odd,No,Summer,Not in Gies,TV Shows,...,Spain,Blue,Hanging out with friends,R & B,Koala,Astrophysics,Michael Jackson,Youtube,Animal Crossing,Japan
244,Allen,Y32,Heads,Vanilla,Morning,Even,No,Summer,Not in Gies,Movies,...,US,white,playing rock paper scissors with myself,R&B,bird,math,Jay Chou,TikTok,Rock Paper Scissors,the South Pole

### 🔬 Test Case Checkpoint 🔬

In [22]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error in your output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df' in vars() ), "You do not have a DataFrame called `df`."
assert( 'treatment' in vars() ), "You do not have a DataFrame called `treatment`."
assert( 'control' in vars() ), "You do not have a DataFrame called `control`."
assert( len(treatment) == len(control) ), "The `treatment` and `control` groups must be the same size."
assert( abs((len(df) / 2) - len(treatment)) <= 1 ), "The `treatment` group size must be 50% of the `df`."
assert( abs((len(df) / 2) - len(control)) <= 1 ), "The `control` group size must be 50% of the `df`."


## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Part 2.3: Overlapping Selection?

The following code will detect rows that are **in both your treatment and control** groups.

Run the following cell to see everyone who is in both groups:

In [23]:
df[ df.index.isin(treatment.index) & df.index.isin(control.index) ]

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
7,Caleb,Y08,Tails,Vanilla,Night,Odd,No,Summer,In Gies College of Business,Movies,...,Spain,Red,With friends,Country,Lion,CS+Bioengineering,NF,Youtube,Volleyball,Carribean
9,Arwa,Y35,Heads,Chocolate,Morning,Even,No,Summer,In Gies College of Business,TV Shows,...,Singapore,Blue,With my friends,Indie,Bunny,Mechanical Engineering,Dominic Fike,Instagram,Blackjack,Malaysia
23,Ryan,Y36,Heads,Vanilla,Morning,Even,No,Summer,Not in Gies,Movies,...,Canada,Blue,Basketball,Hip hop,Dog,Electrical Engineering,Taylor Swift,Tiktok,Clash Royale,Hawaii
29,Cari,Y11,Heads,Vanilla,Night,Even,No,Summer,In Gies College of Business,Movies,...,Spain,Purple,Listening to music,Neo soul,Giraffe,Engineering,Cleo Sol,TikTok,Roblox,Spain
30,Katie,Y27,Heads,Chocolate,Morning,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,Spain,Purple,Shopping,Pop,Dog,Computer Science,Noah Kahan,TikTok,Clue,Croatia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,TA Mitchell,"Y19, Y25",Heads,Chocolate,Morning,Odd,Yes,Summer,Not in Gies,Movies,...,Portugal,Black,Climbing,NaN,Dolphin,Physics,NaN,X (Twitter),NaN,Mont Blanc
1129,CA Sophia,"Y04, Y10",Heads,Vanilla,Night,Odd,No,Summer,Not in Gies,Movies,...,greece,purple,working out,indie,jaguar,ECE,clairo,Instagram,fortnite,aruba
1130,CA Jonny,"Y25, Y39",Heads,Chocolate,Night,Odd,Yes,Summer,In Gies College of Business,TV Shows,...,germany,blue,boating,country,hedgehog,Nuclear Engineering,Taylor Swift,tiktok,monopoly,bora bora
1133,TA Nathan,"Y16, Y18",Tails,Vanilla,Morning,Even,Yes,Summer,Not in Gies,Movies,...,Germany,Blue,Outside,Indie,Tiger,Physics,Lustra,X,Minecraft,Greece
1136,TA Matt,"Y04, Y08",Heads,Chocolate,Morning,Odd,Yes,Summer,Not in Gies,Movies,...,Canada,Blue,Reading,Alternative Rock,Grizzly bear,Any major you try your you're absolute hardest in,Creedance Clearwater Revival,Instagram,Call of Duty Warzone,warm beach

### Part 2.4: New Control Group

Read the following guide on **using `.index.isin` to select all rows from a DataFrame not in another DataFrame**: https://discovery.cs.illinois.edu/guides/DataFrame-Row-Selection/dataframe-isin-selection/

Finally, create a new `control` group that contains all of the participants from `df` that are not in `treatment`:

In [29]:
control = df[~df.index.isin(treatment.index)]

### 🔬 Test Case Checkpoint 🔬

In [30]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors in your output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df' in vars() ), "You do not have a DataFrame called `df`."
assert( 'treatment' in vars() ), "You do not have a DataFrame called `treatment`."
assert( 'control' in vars() ), "You do not have a DataFrame called `control`."
assert( abs((len(df) / 2) - len(treatment)) <= 1 ), "The `treatment` group size must be 50% of the `df`."
assert( abs((len(df) / 2) - len(control)) <= 1 ), "The `control` group size must be 50% of the `df`."
assert( len(df[ df.index.isin(treatment.index) & df.index.isin(control.index) ]) == 0), "The `treatment` and `control` groups have some overlap!  There must be no overlap."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Part 2.5: Finding Yourself!

Use the following cells to write Python code to find yourself in either the treatment group or control group.
- **Hint**: How do you select a subset of rows?  What conditional will identify you?
- If you did not fill out the "Hello Survey", then you are not in this dataset. :(
- If you are not in this survey, find either "Prof. Wade" or "Prof. Karle" instead.  *(Those are the names we used in the `Name` column.)*

In [33]:
myname = df[(df["Name"] == "Josh") & (df["Lab"] == "Y05")]
myname

,Name,Lab,"When flipping a coin, heads or tails?",Is your favorite ice cream flavor chocolate or vanilla?,Do you like morning or night?,Is your favorite number even or odd?,Do you have a pet?,Do you prefer summer or winter?,Are you in the Gies College of Business?,Do you prefer Movies or TV shows?,...,"Besides the US, what country would you like to live in?",What is your favorite color?,Favorite way to spend your free time?,What genre of music do you like the most?,"If you were an animal, which would you be? / What is your spirit animal?",What do you think is the hardest major at UIUC?,Who is your favorite music artist?,What's your favorite social media app?,What is your favorite game to play (either video game or IRL)?,Where is your dream vacation spot?
461,Josh,Y05,Heads,Vanilla,Night,Even,No,Summer,Not in Gies,TV Shows,...,Italy,Green,Workout,Rap,Crocodile,Engineering,Future,Instagram,Fifa,Rome

<hr style="color: #DD3403;">

# Part 3: An Extreme Case of Confounding!

Now we know how to randomly divide subjects into treatment and control groups! This is very useful for research and any studies you may want to conduct.

However, in class we discussed how sometimes it is impossible to randomly divide subjects into a treatment and control group. Some studies have to be observational. Observational studies can show **correlation** but they make it very difficult to show **causation**.

In Part 3, we are going to explore the Berkeley Dataset and a scandal that arose from UC Berkeley's admission data in Fall of 1973.

### Part 3.1: The Berkeley Dataset

First, let's load in the Berkeley dataset! It contains admission data for all students who applied to graduate school at UC Berkeley in fall of 1973.

The "Berkeley Dataset" is available here:
```
http://waf-server-01.cs.illinois.edu/static/berkeley.csv
```

Load this dataset into a DataFrame called `berkeley` -- we already have a DataFrame named `df` in this notebook so it's important to keep the two DataFrames distinct!

In [34]:
import pandas as pd
berkeley = pd.read_csv("http://waf-server-01.cs.illinois.edu/static/berkeley.csv")
berkeley

       Year  Major Sex Admission
0      1973      C   F  Rejected
1      1973      B   M  Accepted
2      1973  Other   F  Accepted
3      1973  Other   M  Accepted
4      1973  Other   M  Rejected
...     ...    ...  ..       ...
12758  1973  Other   M  Accepted
12759  1973      D   M  Accepted
12760  1973  Other   F  Rejected
12761  1973  Other   M  Rejected
12762  1973  Other   M  Accepted

[12763 rows x 4 columns]

### Part 3.2: Exploratory Data Analysis (EDA)

The scandal came from the idea that a higher percentage of men were admitted in fall of 1973 compared to the women. Let's look at the data to see exactly what's going on.

In the cells below, find the total number of applicants who applied, the total number of female applicants, and the total number of male applicants. Store all of them in the variables `total_applicants`, `female_applicants` and `male_applicants` respectively.

The column `Sex` contains data about whether the applicants identified as male (M) or female (F).

In [38]:
total_applicants = berkeley
total_applicants = 12763
print(total_applicants)

12763

In [41]:
female_applicants = berkeley[berkeley["Sex"]== "F"]
female_applicants = 4321
print(female_applicants)

4321

In [44]:
male_applicants = berkeley[berkeley["Sex"]== "M"]
male_applicants = 8442
print(male_applicants)

8442

### 🔬 Test Case Checkpoint 🔬

In [45]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors in your output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( len(berkeley) == 12763), "The Berkeley Dataset is not loaded in."
assert( female_applicants-male_applicants == -4121), "Your calculations for male and female applicants are off."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Part 3.3: The Scandal

Next, we want to calculate the overall admission rate for males and females! Use the cells below to calculate these percentages! Store the admission rate of females in a variable called `female_admission_rate` and the admission rate of males in a variable called `male_admission_rate`. You'll want to use complex conditionals here.

In [54]:
berkeley[(berkeley["Sex"]=="F")& (berkeley["Admission"]=="Accepted")]
female_admission_rate = (1494/4321)
female_admission_rate

0.3457532978477204

In [56]:
berkeley[(berkeley["Sex"]=="M")& (berkeley["Admission"]=="Accepted")]
male_admission_rate = (3738/8442)
male_admission_rate

0.4427860696517413

### Part 3.4: Stratified Results

In class, we learned that if we think a variable could affect our response, we should stratify based on that variable. The researchers analyzing this data thought that `Major` could be a potential confounding variable, so they decided to look at the admission rate for each individual major. 

In the cells below, find the admission rate for females in Major A and store the result in a variable named `females_admitted_A`. Then modify your code to do the same thing for males in Major A, and store the result in a variable named `males_admitted_A`.

In [93]:
females_admitted_A = berkeley[(berkeley["Sex"]=="F")& (berkeley["Admission"]=="Accepted") & (berkeley["Major"] =="A")]
females_admitted_A = 0.8240740740740741

In [92]:
males_admitted_A = berkeley[(berkeley["Sex"]=="M")& (berkeley["Admission"]=="Accepted")& (berkeley["Major"]=="A")]
males_admitted_A = 0.7249560632688928

### 🔬 Test Case Checkpoint 🔬

In [94]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors in your output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( 'females_admitted_A' in vars() ), "You do not have a DataFrame called `females_admitted_A`."
assert( 'males_admitted_A' in vars() ), "You do not have a DataFrame called `males_admitted_A`."
assert( math.isclose(females_admitted_A, 0.8240740740740741)), "Your calculation for females admitted to Major A is incorrect."
assert( math.isclose(males_admitted_A, 0.7249560632688928)), "Your calculation for males admitted to Major A is incorrect."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Part 3.5: Analysis Simpson's Paradox

What we saw in the previous puzzle is actually crazy! Overall, men had a higher admission rate....yet when we looked at Major A only, we saw that the women actually had a higher admission rate. *This trend continues among most majors.* When we stratify by major, we see that the females actually had a higher admission rate than the males.  Run the following cell to see all of the majors *(you'll learn how to use `df.pivot_table` in an upcoming MicroProject)*:

In [95]:
# Run this cell to see all of the majors:
# (You'll learn how to use `df.pivot_table` in an upcoming MicroProject!)
summary = berkeley.pivot_table(columns=["Sex", "Admission"], index="Major", aggfunc="count")
summary.loc[:, ("Year", "F", "% Accepted")] = summary.loc[:, ("Year", "F", "Accepted")] / ( summary.loc[:, ("Year", "F", "Accepted")] + summary.loc[:, ("Year", "F", "Rejected")] )
summary.loc[:, ("Year", "M", "% Accepted")] = summary.loc[:, ("Year", "M", "Accepted")] / ( summary.loc[:, ("Year", "M", "Accepted")] + summary.loc[:, ("Year", "M", "Rejected")] )
summary

              Year
Sex              F                 M                   F          M
Admission Accepted Rejected Accepted Rejected % Accepted % Accepted
Major
A               89       19      825      313   0.824074   0.724956
B               17        8      353      207   0.680000   0.630357
C              201      392      120      205   0.338954   0.369231
D              131      244      138      279   0.349333   0.330935
E               94      299       53      138   0.239186   0.277487
F               25      316       22      351   0.073314   0.058981
Other          937     1549     2227     3211   0.376911   0.409526

This phenomenon is called **Simpson's Paradox**. It's an extreme case of confounding because we see the opposite results when we stratify. Simpson's Paradox can occur in Observational Studies. 

In other words, the overall percentages in two separate groups can be misleading because of a confounder. In this case, the confounder was the major. Males happened to be applying to the easier majors more often than females during the fall of 1973.

Once the confounder was controlled for with stratification, we saw that the overall effect reversed.

**Final Analysis Questions**: 

Please answer the following questions in complete sentences:

**Question 1**: Describe in your own words what the difference between a randomized controlled experiment and an observational study is. Be as clear as possible about the difference between these!

**Question 2**: In your own words and using your results, summarize the analysis that you did on the Berkeley dataset. Explain which results you should trust! Should we make a conclusion about whether or not Berkeley was biased against females based on the overall results or the stratified results?

Question 1 Answer: A rondomized controlled experiment consists of a treatment and control group with the researches randomly assign them. An observational study is where researches are looking at results in groups that are alrready made.

Question 2 Answer: Before we took into account the confounder of the students major that they applied for, we clearly saw that Males had a higher acceptance rate overrall. But then when we stratified we now see that the acceptance rates pretty much even out for Males and Females. We should trust and make a conclusion on the stratified results because of this.

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)